sudo: required

dist: trusty

language: python

services:
  - docker

before_install:
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-engine
- docker-compose build
- docker-compose -f docker-compose.yml -f docker-compose.testing.yml run api_auth flask initdb

script:
- docker-compose -f docker-compose.yml -f docker-compose.testing.yml run api_auth pytest api_auth/api_auth/tests -v
