sudo: required

dist: trusty

language: python

services:
  - docker

before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce
- docker-compose -f docker-compose.yml -f docker-compose.testing.yml run api_auth flask initdb

script:
- docker-compose -f docker-compose.yml -f docker-compose.testing.yml run api_auth pytest api_auth/api_auth/tests -v
