sudo: required

dist: trusty

language: python

services:
  - docker

before_install:
- docker-compose build

script:
- docker-compose -f docker-compose.yml -f docker-compose.testing.yml run api_auth pytest api_auth/api_auth/tests -v
