version: '3'

services:
  simplepages:
    volumes:
      - ./simplepages/simplepages:/app/src
    ports:
      - 5000:80
  
  api-finances:
    volumes:
      - ./api-finances/api-finances:/app/src
    ports:
      - 5001:80
