version: '3'

services:
  database:
    image: postgres

  api_auth:
    build: ./api_auth
    depends_on:
      - database

  api-finances:
    build: ./api-finances
    depends_on:
      - database

  simplepages:
    build: ./simplepages
    depends_on:
      - api-finances

  nginx:
    build: ./nginx
    ports:
      - 80:8000
    depends_on:
      - simplepages
