version: '3'

services:
  api-finances:
    build: ./api-finances

  simplepages:
    build: ./simplepages
    depends_on:
      - api-finances

  nginx:
    build: ./nginx
    ports:
      - 80:8000
    depends_on:
      - simplepages
