version: '3'

services:
  database:
    ports:
      - 5432:5432

  api_auth:
    command: 'flask run --host=0.0.0.0 --port=80'
    volumes:
      - ./api_auth:/app/api_auth
    ports:
      - 5002:80
    environment:
      - FLASK_DEBUG=1
      - FLASK_CONFIG_OVERRIDE=/app/api_auth/config/dev.cfg

  api_finances:
    command: 'flask run --host=0.0.0.0 --port=80'
    volumes:
      - ./api_finances:/app/api_finances
    ports:
      - 5001:80

  simplepages:
    command: 'flask run --host=0.0.0.0 --port=80'
    volumes:
      - ./simplepages/simplepages:/app/src
    ports:
      - 5000:80
