version: '3'

services:
  database:
    image: postgres

  api:
    build: ./api
    depends_on:
      - database

  api_auth:
    build: ./api_auth
    depends_on:
      - database

  finances:
    build: ./finances
    depends_on:
      - database

  simplepages:
    build: ./simplepages
    depends_on:
      - finances

  nginx:
    build: ./nginx
    ports:
      - 80:8000
    depends_on:
      - simplepages
      - finances
