version: '3'

services:
  database:
    image: postgres

  api_auth:
    build: ./api_auth
    depends_on:
      - database

  api_finances:
    build: ./api_finances
    depends_on:
      - database

  simplepages:
    build: ./simplepages
    depends_on:
      - api_finances

  nginx:
    build: ./nginx
    ports:
      - 80:8000
    depends_on:
      - simplepages
      - api_finances
